import { LandingLayout } from "@/components/LandingLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bell, Target, Shield, BarChart, HelpCircle, ArrowRight, CheckCircle2, AlertTriangle, TrendingUp, Activity } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";

export default function TradingSignalsPage() {
  const signalComponents = [
    {
      title: "Entry Point",
      icon: Target,
      description: "Precise price level to enter the trade",
      details: "Based on technical analysis, chart patterns, and indicator confluence. Signals specify exact entry price or trigger conditions (e.g., 'Buy above 1.1050'). Professional signals include both market orders and pending orders.",
      importance: "Critical"
    },
    {
      title: "Stop Loss",
      icon: Shield,
      description: "Risk management level to limit losses",
      details: "Placed below support (for buys) or above resistance (for sells). Protects capital if market moves against the position. Typically 20-50 pips depending on volatility and timeframe. Never trade without a stop loss.",
      importance: "Mandatory"
    },
    {
      title: "Take Profit",
      icon: Target,
      description: "Target price level to secure profits",
      details: "Set at key resistance/support levels or using risk-reward ratios. Professional signals often include multiple TP levels (TP1, TP2, TP3) for partial profit taking. Example: Close 50% at TP1, 30% at TP2, let 20% run to TP3.",
      importance: "Critical"
    },
    {
      title: "Risk/Reward Ratio",
      icon: BarChart,
      description: "Potential profit vs potential loss",
      details: "Minimum 1:2 ratio recommended (risk $1 to make $2). Professional traders target 1:3 or higher ratios. Crucial for long-term profitability even with 50% win rate. Calculate: (TP - Entry) / (Entry - SL) for longs.",
      importance: "Essential"
    }
  ];

  const signalTypes = [
    {
      name: "Technical Signals",
      description: "Based on chart patterns, indicators, and price action",
      examples: ["RSI divergence trades", "Moving average crossovers", "Breakout signals", "Support/resistance bounces"],
      accuracy: "65-75%",
      bestFor: "Swing and day trading",
      timeframe: "M15 to Daily"
    },
    {
      name: "Fundamental Signals",
      description: "Driven by economic data and news events",
      examples: ["Interest rate decisions", "NFP trading signals", "Central bank announcements", "GDP release trades"],
      accuracy: "60-70%",
      bestFor: "Position trading",
      timeframe: "H4 to Weekly"
    },
    {
      name: "Algorithmic Signals",
      description: "Generated by automated trading systems",
      examples: ["Machine learning predictions", "Statistical arbitrage", "Multi-indicator algorithms", "Backtested strategies"],
      accuracy: "55-80% (varies)",
      bestFor: "All trading styles",
      timeframe: "All timeframes"
    },
    {
      name: "Price Action Signals",
      description: "Pure price movement without indicators",
      examples: ["Pin bar reversals", "Engulfing patterns", "Inside bars", "Trend line breaks"],
      accuracy: "70-80%",
      bestFor: "Experienced traders",
      timeframe: "H1 to Daily"
    }
  ];

  const signalQuality = [
    {
      factor: "Track Record Transparency",
      good: "Verified results with win rate, average R:R, drawdown stats",
      bad: "No historical performance or cherry-picked winners only"
    },
    {
      factor: "Risk Management",
      good: "Clear SL/TP levels, position sizing guidance, max 2-3% risk per trade",
      bad: "No stop loss, 'hold until profit', or risky martingale strategies"
    },
    {
      factor: "Signal Frequency",
      good: "Quality over quantity: 3-10 signals per week with high probability",
      bad: "20+ signals daily (overtrading), inconsistent quality"
    },
    {
      factor: "Transparency & Timing",
      good: "Signals sent before market moves, real-time alerts, reasoning provided",
      bad: "Signals sent after move started, delayed notifications, no rationale"
    },
    {
      factor: "Realistic Claims",
      good: "50-70% win rate with 1:2+ R:R, acknowledges losses",
      bad: "90%+ win rate claims, 'guaranteed profits', no losing trades shown"
    }
  ];

  const usingSignals = [
    {
      step: "1. Verify Signal Quality",
      action: "Check provider's track record, verify win rate and R:R ratio",
      tip: "Demand verified results, not screenshots"
    },
    {
      step: "2. Understand the Setup",
      action: "Read the signal reasoning - why this trade, what's the setup?",
      tip: "Never blindly follow; learn from each signal"
    },
    {
      step: "3. Check Your Chart",
      action: "Confirm the setup matches on your platform before entering",
      tip: "Prices can vary between brokers"
    },
    {
      step: "4. Calculate Position Size",
      action: "Use 1-2% risk per trade based on SL distance",
      tip: "Never risk more than 2% on a single signal"
    },
    {
      step: "5. Enter with Confirmation",
      action: "Wait for signal trigger (price above X, candle close, etc.)",
      tip: "Premature entry increases risk"
    },
    {
      step: "6. Set SL/TP Immediately",
      action: "Place stop loss and take profit as soon as trade is open",
      tip: "Never skip this step"
    },
    {
      step: "7. Manage the Trade",
      action: "Trail stops, take partial profits at TP1/TP2 if multiple levels",
      tip: "Stick to the plan, avoid emotional decisions"
    },
    {
      step: "8. Log Results",
      action: "Track every signal's outcome for performance analysis",
      tip: "Identify which signal types work best for you"
    }
  ];

  const faqs = [
    {
      question: "Are trading signals worth paying for?",
      answer: "It depends on the provider's track record and your goals. Quality signal services with verified 60%+ win rates and 1:2+ R:R can be worth it for beginners learning trading or busy professionals. However, many free signals exist, and developing your own analysis skills is ultimately more valuable. Never rely 100% on signals - use them as learning tools and always verify setups yourself before entering trades."
    },
    {
      question: "What win rate should I expect from trading signals?",
      answer: "Realistic expectations: 55-70% win rate for quality signals. With proper risk/reward (1:2 minimum), even 50% win rate is profitable. Beware of services claiming 80-90%+ win rates - they're often manipulated or cherry-picked. Focus on risk/reward ratio over win rate. A 40% win rate with 1:3 R:R (risk $1 to make $3) is more profitable than 70% win rate with 1:1 R:R."
    },
    {
      question: "How do I know if a signal provider is legitimate?",
      answer: "Check for: 1) Verified track record on third-party platforms (MyFXBook, FX Blue), 2) Transparent performance metrics (win rate, drawdown, average R:R), 3) Realistic claims (no guaranteed profits), 4) Clear risk management (always includes SL), 5) Reasoning behind each signal (not just entry/exit numbers), 6) Consistent signal quality over months, not weeks. Red flags: No track record, delayed signals, no stop losses, 90%+ win rate claims."
    },
    {
      question: "Can I automate trading signals with a robot/EA?",
      answer: "Yes, but with caution. Some providers offer APIs or Telegram bots for auto-execution. Benefits: Faster execution, no emotional trading. Risks: Technical failures, slippage, broker compatibility issues. Only automate signals from providers with long, verified track records. Always test on demo first for 1-2 months. Keep position sizes small (max 1% risk). Monitor automated trades daily - never 'set and forget.'"
    },
    {
      question: "Should I take every signal from my provider?",
      answer: "No. Filter signals based on: 1) Your risk tolerance (skip signals with >50 pip SL if you're conservative), 2) Market conditions (avoid ranging market signals during low volatility), 3) Your trading session (skip Tokyo signals if you trade London/NY), 4) Confluence with your own analysis (signal + your confirmation = higher probability). Start with cherry-picking the highest quality setups (strong R:R, clear patterns) until you build confidence."
    },
    {
      question: "What's the difference between free and paid signals?",
      answer: "Free signals: Often delayed, fewer per week, less detail, may be marketing for paid tiers, inconsistent quality. Paid signals ($50-200/month): Faster delivery, more signals, detailed analysis, multiple TP levels, trade management updates, community support. However, paid ≠ better. Some free providers outperform paid ones. Evaluate based on verified track record, not price. Many paid services offer free trials - use them to test quality before committing."
    },
    {
      question: "How should I manage multiple take profit levels?",
      answer: "Standard approach: Close 50% at TP1 (secure profits), 30% at TP2 (lock in more gains), let 20% run to TP3 or trail stop (maximize winners). This balances profit-taking with letting winners run. When TP1 hits, move SL to breakeven to make trade risk-free. Alternative: Close 100% at TP1 for beginners (simpler, less stress). Advanced: Trail stop after TP1 instead of fixed TP2/TP3 (can capture larger moves). Choose based on your risk tolerance and trading style."
    }
  ];

  return (
    <LandingLayout>
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <Badge className="mb-4" data-testid="badge-trading-signals">Market Education</Badge>
            <h1 className="text-4xl font-bold mb-4">Trading Signals Explained</h1>
            <p className="text-lg text-muted-foreground max-w-3xl mx-auto">
              Learn how professional trading signals work, their components, evaluation criteria, and how to use them effectively to enhance your trading performance without blindly following.
            </p>
          </div>

          {/* Signal Example */}
          <Card className="mb-12">
            <CardHeader>
              <div className="flex items-center gap-3">
                <Bell className="w-6 h-6 text-primary" />
                <div>
                  <CardTitle>Example Professional Trading Signal</CardTitle>
                  <CardDescription>Complete signal format with all critical components</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="bg-muted rounded-lg p-6 space-y-4">
                <div className="flex items-center justify-between pb-3 border-b">
                  <div>
                    <p className="text-sm text-muted-foreground">Instrument</p>
                    <p className="text-2xl font-bold">EUR/USD</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Direction</p>
                    <p className="text-2xl font-bold text-green-500">BUY</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Timeframe</p>
                    <p className="text-2xl font-bold">H4</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Risk/Reward</p>
                    <p className="text-2xl font-bold text-primary">1:3</p>
                  </div>
                </div>
                
                <div className="grid md:grid-cols-4 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Entry Price</p>
                    <p className="text-lg font-semibold">1.1050</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Stop Loss</p>
                    <p className="text-lg font-semibold text-red-500">1.1000 (-50 pips)</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Take Profit 1</p>
                    <p className="text-lg font-semibold text-green-500">1.1100 (+50 pips)</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Take Profit 2</p>
                    <p className="text-lg font-semibold text-green-500">1.1150 (+100 pips)</p>
                  </div>
                </div>

                <div className="pt-3 border-t">
                  <p className="text-sm font-medium mb-2">Signal Reasoning:</p>
                  <p className="text-sm text-muted-foreground">
                    EUR/USD bouncing from major support at 1.1000 (tested 3x in past month). RSI showing bullish divergence on H4. 
                    Price above 50 EMA. Target resistance at 1.1100 and 1.1150. Close 50% at TP1, trail stop for TP2.
                  </p>
                </div>

                <div className="flex items-center gap-2 pt-2">
                  <Badge>Technical Setup</Badge>
                  <Badge variant="outline">Bullish Divergence</Badge>
                  <Badge variant="outline">Support Bounce</Badge>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Signal Components */}
          <div className="mb-12">
            <h2 className="text-2xl font-bold mb-6 text-center">Essential Signal Components</h2>
            <div className="grid md:grid-cols-2 gap-6">
              {signalComponents.map((component) => {
                const Icon = component.icon;
                return (
                  <Card key={component.title} data-testid={`card-component-${component.title.toLowerCase().replace(/\s+/g, '-')}`}>
                    <CardHeader>
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-primary/10 rounded-lg">
                          <Icon className="w-6 h-6 text-primary" />
                        </div>
                        <div className="flex-1">
                          <div className="flex items-center justify-between">
                            <CardTitle>{component.title}</CardTitle>
                            <Badge variant="outline">{component.importance}</Badge>
                          </div>
                          <CardDescription>{component.description}</CardDescription>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground">{component.details}</p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>

          {/* Signal Types */}
          <Card className="mb-12">
            <CardHeader>
              <div className="flex items-center gap-2">
                <Activity className="w-5 h-5 text-primary" />
                <CardTitle>Types of Trading Signals</CardTitle>
              </div>
              <CardDescription>Different signal methodologies and their characteristics</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                {signalTypes.map((type, index) => (
                  <div key={index} className="border-l-4 border-primary pl-4">
                    <div className="flex items-start justify-between mb-2">
                      <div>
                        <h3 className="font-semibold text-lg">{type.name}</h3>
                        <p className="text-sm text-muted-foreground">{type.description}</p>
                      </div>
                      <Badge>{type.accuracy}</Badge>
                    </div>
                    <div className="grid sm:grid-cols-2 gap-4 mt-3">
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-1">Examples:</p>
                        <ul className="space-y-1">
                          {type.examples.map((example, i) => (
                            <li key={i} className="text-sm flex items-center gap-1">
                              <CheckCircle2 className="w-3 h-3 text-primary" />
                              {example}
                            </li>
                          ))}
                        </ul>
                      </div>
                      <div>
                        <p className="text-xs font-medium text-muted-foreground mb-1">Best For:</p>
                        <p className="text-sm mb-2">{type.bestFor}</p>
                        <p className="text-xs font-medium text-muted-foreground mb-1">Timeframe:</p>
                        <p className="text-sm">{type.timeframe}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Signal Quality Evaluation */}
          <Card className="mb-12">
            <CardHeader>
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-primary" />
                <CardTitle>Evaluating Signal Quality</CardTitle>
              </div>
              <CardDescription>How to identify high-quality signal providers</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {signalQuality.map((item, index) => (
                  <div key={index} className="grid sm:grid-cols-2 gap-4">
                    <div className="p-4 border-l-4 border-green-500 bg-green-50 dark:bg-green-950/20 rounded">
                      <p className="font-semibold text-green-700 dark:text-green-400 mb-1">✓ {item.factor}</p>
                      <p className="text-sm text-green-600 dark:text-green-500">{item.good}</p>
                    </div>
                    <div className="p-4 border-l-4 border-red-500 bg-red-50 dark:bg-red-950/20 rounded">
                      <p className="font-semibold text-red-700 dark:text-red-400 mb-1">✗ Red Flag</p>
                      <p className="text-sm text-red-600 dark:text-red-500">{item.bad}</p>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Using Signals */}
          <Card className="mb-12">
            <CardHeader>
              <CardTitle>Step-by-Step: How to Use Trading Signals</CardTitle>
              <CardDescription>Follow this process for every signal you receive</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {usingSignals.map((item, index) => (
                  <div key={index} className="flex gap-4">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center font-bold">
                      {index + 1}
                    </div>
                    <div className="flex-1">
                      <h4 className="font-semibold mb-1">{item.step.replace(/^\d+\.\s/, '')}</h4>
                      <p className="text-sm text-muted-foreground mb-1">{item.action}</p>
                      <Alert className="mt-2">
                        <AlertDescription className="text-sm">
                          <strong>Pro Tip:</strong> {item.tip}
                        </AlertDescription>
                      </Alert>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* FAQ */}
          <Card className="mb-12">
            <CardHeader>
              <div className="flex items-center gap-2">
                <HelpCircle className="w-5 h-5 text-primary" />
                <CardTitle>Frequently Asked Questions</CardTitle>
              </div>
            </CardHeader>
            <CardContent>
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((faq, index) => (
                  <AccordionItem key={index} value={`item-${index}`} data-testid={`faq-item-${index}`}>
                    <AccordionTrigger className="text-left">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                      {faq.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>

          {/* Warning */}
          <Alert className="mb-8">
            <AlertTriangle className="w-4 h-4" />
            <AlertDescription>
              <strong>Important:</strong> Trading signals should be used as learning tools and trade ideas, not blindly followed. 
              Always verify setups on your charts, understand the reasoning, and manage risk properly. Past performance doesn't guarantee future results.
            </AlertDescription>
          </Alert>

          {/* CTA */}
          <div className="bg-gradient-to-r from-primary/10 to-primary/5 rounded-lg p-8 text-center">
            <h2 className="text-2xl font-bold mb-4">Learn to Generate Your Own Signals</h2>
            <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
              While signals can help, developing your own analysis skills leads to long-term trading success. Explore our comprehensive education courses.
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Button size="lg" data-testid="button-courses">
                View Trading Courses
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
              <Button size="lg" variant="outline" data-testid="button-start-trading">
                Start Trading
              </Button>
            </div>
          </div>
        </div>
      </div>
    </LandingLayout>
  );
}
