import { LandingLayout } from "@/components/LandingLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Bell, Target, Shield, BarChart } from "lucide-react";

export default function TradingSignalsPage() {
  const signalComponents = [
    {
      title: "Entry Point",
      icon: Target,
      description: "Precise price level to enter the trade",
      details: "Based on technical analysis, chart patterns, and indicator confluence. Signals specify exact entry price or trigger conditions (e.g., 'Buy above 1.1050')."
    },
    {
      title: "Stop Loss",
      icon: Shield,
      description: "Risk management level to limit losses",
      details: "Placed below support (for buys) or above resistance (for sells). Protects capital if market moves against the position. Typically 20-50 pips depending on volatility."
    },
    {
      title: "Take Profit",
      icon: Target,
      description: "Target price level to secure profits",
      details: "Set at key resistance/support levels or using risk-reward ratios. Professional signals often include multiple TP levels for partial profit taking."
    },
    {
      title: "Risk/Reward Ratio",
      icon: BarChart,
      description: "Potential profit vs potential loss",
      details: "Minimum 1:2 ratio recommended (risk $1 to make $2). Professional traders target 1:3 or higher ratios. Crucial for long-term profitability even with 50% win rate."
    }
  ];

  const signalTypes = [
    {
      name: "Technical Signals",
      description: "Based on chart patterns, indicators, and price action",
      examples: ["RSI divergence trades", "Moving average crossovers", "Breakout signals", "Support/resistance bounces"]
    },
    {
      name: "Fundamental Signals",
      description: "Driven by economic data and news events",
      examples: ["Interest rate decisions", "NFP trading signals", "Central bank announcements", "GDP release trades"]
    },
    {
      name: "Algorithmic Signals",
      description: "Generated by automated trading systems",
      examples: ["Machine learning predictions", "Statistical arbitrage", "Multi-indicator algorithms", "Backtested strategies"]
    }
  ];

  return (
    <LandingLayout>
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold mb-4">Trading Signals</h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Learn how professional trading signals work, their components, and how to use them effectively to enhance your trading performance.
            </p>
          </div>

          <div className="mb-12">
            <h2 className="text-2xl font-bold mb-6 text-center">Signal Components</h2>
            <div className="grid md:grid-cols-2 gap-6">
              {signalComponents.map((component) => {
                const Icon = component.icon;
                return (
                  <Card key={component.title} data-testid={`card-component-${component.title.toLowerCase().replace(/\s+/g, '-')}`}>
                    <CardHeader>
                      <div className="flex items-center gap-3">
                        <div className="p-2 bg-primary/10 rounded-lg">
                          <Icon className="w-6 h-6 text-primary" />
                        </div>
                        <div>
                          <CardTitle>{component.title}</CardTitle>
                          <CardDescription>{component.description}</CardDescription>
                        </div>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground">{component.details}</p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>

          <Card className="mb-12">
            <CardHeader>
              <div className="flex items-center gap-3">
                <Bell className="w-6 h-6 text-primary" />
                <div>
                  <CardTitle>Example Trading Signal</CardTitle>
                  <CardDescription>Typical signal format with all key components</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="bg-muted rounded-lg p-6 space-y-3">
                <div className="flex items-center justify-between pb-3 border-b">
                  <div>
                    <p className="text-sm text-muted-foreground">Instrument</p>
                    <p className="text-xl font-bold">EUR/USD</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Direction</p>
                    <p className="text-xl font-bold text-green-500">BUY</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Timeframe</p>
                    <p className="text-xl font-bold">H4</p>
                  </div>
                </div>
                
                <div className="grid md:grid-cols-3 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Entry Price</p>
                    <p className="text-lg font-semibold">1.1050</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Stop Loss</p>
                    <p className="text-lg font-semibold text-red-500">1.1000</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground mb-1">Take Profit</p>
                    <p className="text-lg font-semibold text-green-500">1.1150</p>
                  </div>
                </div>

                <div className="pt-3 border-t">
                  <p className="text-sm text-muted-foreground mb-1">Analysis</p>
                  <p className="text-sm">
                    EUR/USD bouncing from key support at 1.1050 with bullish RSI divergence on H4. Target previous resistance at 1.1150. Risk/Reward: 1:2 (50 pips risk, 100 pips profit).
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="mb-12">
            <h2 className="text-2xl font-bold mb-6">Types of Trading Signals</h2>
            <div className="grid md:grid-cols-3 gap-6">
              {signalTypes.map((type) => (
                <Card key={type.name}>
                  <CardHeader>
                    <CardTitle className="text-lg">{type.name}</CardTitle>
                    <CardDescription>{type.description}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {type.examples.map((example, index) => (
                        <li key={index} className="flex items-center gap-2 text-sm">
                          <div className="w-1.5 h-1.5 rounded-full bg-primary" />
                          <span>{example}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            <Card>
              <CardHeader>
                <CardTitle>How to Use Signals Effectively</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <div className="flex items-start gap-2">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center flex-shrink-0 text-xs font-bold">1</div>
                  <p><span className="font-semibold">Verify the Signal:</span> Check if price is near the entry level and market conditions align</p>
                </div>
                <div className="flex items-start gap-2">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center flex-shrink-0 text-xs font-bold">2</div>
                  <p><span className="font-semibold">Manage Position Size:</span> Never risk more than 1-2% of account per signal</p>
                </div>
                <div className="flex items-start gap-2">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center flex-shrink-0 text-xs font-bold">3</div>
                  <p><span className="font-semibold">Set Stop Loss Immediately:</span> Always use the recommended SL, don't move it wider</p>
                </div>
                <div className="flex items-start gap-2">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center flex-shrink-0 text-xs font-bold">4</div>
                  <p><span className="font-semibold">Be Patient:</span> Let the trade play out, don't exit early due to minor fluctuations</p>
                </div>
                <div className="flex items-start gap-2">
                  <div className="w-6 h-6 rounded-full bg-primary text-primary-foreground flex items-center justify-center flex-shrink-0 text-xs font-bold">5</div>
                  <p><span className="font-semibold">Track Performance:</span> Keep a journal of signal results to evaluate quality</p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Important Disclaimers</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3 text-sm">
                <div className="p-3 bg-destructive/10 rounded-lg">
                  <p className="font-semibold mb-1">No Guarantee of Profit</p>
                  <p className="text-muted-foreground">Signals are not guaranteed to be profitable. Markets can move unexpectedly.</p>
                </div>
                <div className="p-3 bg-destructive/10 rounded-lg">
                  <p className="font-semibold mb-1">Past Performance ≠ Future Results</p>
                  <p className="text-muted-foreground">Historical win rate doesn't predict future signal accuracy.</p>
                </div>
                <div className="p-3 bg-destructive/10 rounded-lg">
                  <p className="font-semibold mb-1">Use Proper Risk Management</p>
                  <p className="text-muted-foreground">Always follow position sizing rules regardless of signal confidence.</p>
                </div>
                <div className="p-3 bg-destructive/10 rounded-lg">
                  <p className="font-semibold mb-1">Not Financial Advice</p>
                  <p className="text-muted-foreground">Signals are for educational purposes. Trade at your own risk.</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </LandingLayout>
  );
}
